import type { Brand, Perfume, Perfumer, ScentDNAProfile, UserProfile, WeatherSnapshot } from "@/utils/types";
import { vectorFromArray } from "@/utils/helpers";

export const mockPerfumes: Perfume[] = [
  {
    id: "bleu-de-chanel-edp",
    slug: "bleu-de-chanel-edp",
    name: "Bleu de Chanel",
    brand: "Chanel",
    brandSlug: "chanel",
    sourceUrl: "https://www.fragrantica.com",
    country: "France",
    imageUrl: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=800&q=80",
    gender: "men",
    year: 2014,
    concentration: "EDP",
    perfumers: ["Jacques Polge"],
    topNotes: ["Grapefruit", "Lemon", "Mint"],
    midNotes: ["Ginger", "Jasmine", "Nutmeg"],
    baseNotes: ["Sandalwood", "Cedar", "Incense"],
    families: ["Fresh", "Woody", "Citrus"],
    longevity: 8.1,
    projection: 6.4,
    seasons: ["Spring", "Summer", "Fall"],
    occasions: ["Daily", "Office", "Date Night"],
    impressions: ["Clean", "Professional", "Elegant"],
    priceRange: "$$",
    scentVector: [85, 60, 10, 70, 15, 20, 5, 35, 15, 5, 5, 10, 5, 5],
    ratingAvg: 4.6,
    ratingCount: 829,
  },
  {
    id: "another-13",
    slug: "another-13",
    name: "Another 13",
    brand: "Le Labo",
    brandSlug: "le-labo",
    sourceUrl: "https://www.fragrantica.com",
    country: "United States",
    imageUrl: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=800&q=80",
    gender: "unisex",
    year: 2010,
    concentration: "EDP",
    perfumers: ["Nathalie Lorson"],
    topNotes: ["Pear", "Citrus"],
    midNotes: ["Jasmine", "Apple"],
    baseNotes: ["Musk", "Iso E Super", "Amber"],
    families: ["Musky", "Fresh", "Amber"],
    longevity: 7.3,
    projection: 5.8,
    seasons: ["Spring", "Summer", "Fall"],
    occasions: ["Daily", "Office", "Special"],
    impressions: ["Modern", "Clean", "Skin Scent"],
    priceRange: "$$$",
    scentVector: [72, 28, 18, 26, 4, 18, 6, 82, 34, 6, 0, 16, 0, 8],
    ratingAvg: 4.5,
    ratingCount: 412,
  },
  {
    id: "grand-soir",
    slug: "grand-soir",
    name: "Grand Soir",
    brand: "Maison Francis Kurkdjian",
    brandSlug: "maison-francis-kurkdjian",
    sourceUrl: "https://www.fragrantica.com",
    country: "France",
    imageUrl: "https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?auto=format&fit=crop&w=800&q=80",
    gender: "unisex",
    year: 2016,
    concentration: "EDP",
    perfumers: ["Francis Kurkdjian"],
    topNotes: ["Cistus", "Orange"],
    midNotes: ["Benzoin", "Lavender"],
    baseNotes: ["Amber", "Vanilla", "Tonka"],
    families: ["Amber", "Vanilla", "Oriental"],
    longevity: 9.1,
    projection: 7.8,
    seasons: ["Fall", "Winter"],
    occasions: ["Night Out", "Special", "Date Night"],
    impressions: ["Warm", "Sexy", "Luxurious"],
    priceRange: "$$$$",
    scentVector: [10, 18, 68, 8, 16, 0, 8, 18, 88, 76, 0, 8, 4, 72],
    ratingAvg: 4.8,
    ratingCount: 251,
  },
  {
    id: "wood-sage-sea-salt",
    slug: "wood-sage-sea-salt",
    name: "Wood Sage & Sea Salt",
    brand: "Jo Malone",
    brandSlug: "jo-malone",
    sourceUrl: "https://www.fragrantica.com",
    country: "United Kingdom",
    imageUrl: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=800&q=80",
    gender: "women",
    year: 2014,
    concentration: "Cologne",
    perfumers: ["Christine Nagel"],
    topNotes: ["Ambrette", "Sea Salt"],
    midNotes: ["Sage"],
    baseNotes: ["Seaweed", "Grapefruit"],
    families: ["Aquatic", "Fresh", "Woody"],
    longevity: 5.3,
    projection: 4.2,
    seasons: ["Spring", "Summer"],
    occasions: ["Daily", "Office", "Sport"],
    impressions: ["Airy", "Fresh", "Minimal"],
    priceRange: "$$$",
    scentVector: [76, 26, 8, 18, 4, 74, 2, 18, 4, 0, 0, 4, 0, 0],
    ratingAvg: 4.2,
    ratingCount: 368,
  },
  {
    id: "gentle-fluidity-silver",
    slug: "gentle-fluidity-silver",
    name: "Gentle Fluidity Silver",
    brand: "Maison Francis Kurkdjian",
    brandSlug: "maison-francis-kurkdjian",
    sourceUrl: "https://www.fragrantica.com",
    country: "France",
    imageUrl: "https://images.unsplash.com/photo-1588405748880-12d1d2a59b17?auto=format&fit=crop&w=800&q=80",
    gender: "men",
    year: 2019,
    concentration: "EDP",
    perfumers: ["Francis Kurkdjian"],
    topNotes: ["Juniper", "Nutmeg"],
    midNotes: ["Coriander"],
    baseNotes: ["Musk", "Amber Woods", "Vanilla"],
    families: ["Fresh", "Spicy", "Musky"],
    longevity: 7.9,
    projection: 6.2,
    seasons: ["Spring", "Fall"],
    occasions: ["Office", "Daily", "Special"],
    impressions: ["Crisp", "Metallic", "Polished"],
    priceRange: "$$$$",
    scentVector: [68, 34, 14, 18, 52, 10, 4, 56, 22, 10, 0, 6, 0, 12],
    ratingAvg: 4.7,
    ratingCount: 198,
  },
  {
    id: "gris-dior",
    slug: "gris-dior",
    name: "Gris Dior",
    brand: "Dior",
    brandSlug: "dior",
    sourceUrl: "https://www.fragrantica.com",
    country: "France",
    imageUrl: "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=800&q=80",
    gender: "women",
    year: 2013,
    concentration: "EDP",
    perfumers: ["François Demachy"],
    topNotes: ["Bergamot"],
    midNotes: ["Rose", "Patchouli"],
    baseNotes: ["Amber", "Oakmoss"],
    families: ["Floral", "Woody", "Amber"],
    longevity: 8.4,
    projection: 6.1,
    seasons: ["Spring", "Fall", "Winter"],
    occasions: ["Office", "Special", "Date Night"],
    impressions: ["Elegant", "Refined", "Powdery"],
    priceRange: "$$$$",
    scentVector: [26, 38, 18, 18, 4, 0, 26, 22, 36, 8, 0, 64, 6, 24],
    ratingAvg: 4.6,
    ratingCount: 123,
  },
  {
    id: "bal-d-afrique",
    slug: "bal-d-afrique",
    name: "Bal d'Afrique",
    brand: "Byredo",
    brandSlug: "byredo",
    sourceUrl: "https://www.fragrantica.com",
    country: "Sweden",
    imageUrl: "https://images.unsplash.com/photo-1611078489935-0cb964de46d6?auto=format&fit=crop&w=800&q=80",
    gender: "women",
    year: 2009,
    concentration: "EDP",
    perfumers: ["Jérôme Epinette"],
    topNotes: ["Bergamot", "Lemon", "Black Currant"],
    midNotes: ["Violet", "Jasmine", "Cyclamen"],
    baseNotes: ["Vetiver", "Musk", "Amber"],
    families: ["Citrus", "Woody", "Musky"],
    longevity: 7.2,
    projection: 5.9,
    seasons: ["Spring", "Summer", "Fall"],
    occasions: ["Daily", "Office", "Special"],
    impressions: ["Radiant", "Soft", "Polished"],
    priceRange: "$$$$",
    scentVector: [66, 34, 12, 74, 8, 10, 12, 46, 18, 6, 0, 34, 0, 10],
    ratingAvg: 4.5,
    ratingCount: 276,
  },
  {
    id: "tam-dao-edp",
    slug: "tam-dao-edp",
    name: "Tam Dao",
    brand: "Diptyque",
    brandSlug: "diptyque",
    sourceUrl: "https://www.fragrantica.com",
    country: "France",
    imageUrl: "https://images.unsplash.com/photo-1595425964073-9b7d60884b83?auto=format&fit=crop&w=800&q=80",
    gender: "men",
    year: 2013,
    concentration: "EDP",
    perfumers: ["Daniela Andrier"],
    topNotes: ["Italian Cypress", "Myrtle"],
    midNotes: ["Sandalwood", "Cedar"],
    baseNotes: ["Amberwood", "Spices", "Rosewood"],
    families: ["Woody", "Spicy", "Amber"],
    longevity: 8.5,
    projection: 5.7,
    seasons: ["Fall", "Winter", "Spring"],
    occasions: ["Daily", "Office", "Quiet Evenings"],
    impressions: ["Meditative", "Dry", "Elegant"],
    priceRange: "$$$",
    scentVector: [24, 86, 6, 8, 34, 0, 6, 18, 24, 0, 18, 4, 2, 16],
    ratingAvg: 4.7,
    ratingCount: 311,
  },
  {
    id: "portrait-of-a-lady",
    slug: "portrait-of-a-lady",
    name: "Portrait of a Lady",
    brand: "Frederic Malle",
    brandSlug: "frederic-malle",
    sourceUrl: "https://www.fragrantica.com",
    country: "France",
    imageUrl: "https://images.unsplash.com/photo-1590736969955-71cc94901144?auto=format&fit=crop&w=800&q=80",
    gender: "women",
    year: 2010,
    concentration: "EDP",
    perfumers: ["Dominique Ropion"],
    topNotes: ["Rose", "Clove", "Raspberry"],
    midNotes: ["Patchouli", "Black Currant", "Incense"],
    baseNotes: ["Sandalwood", "Musk", "Benzoin"],
    families: ["Floral", "Amber", "Spicy"],
    longevity: 9.4,
    projection: 8.3,
    seasons: ["Fall", "Winter"],
    occasions: ["Date Night", "Special", "Night Out"],
    impressions: ["Dramatic", "Velvet", "Confident"],
    priceRange: "$$$$",
    scentVector: [8, 22, 24, 0, 44, 0, 12, 18, 56, 8, 0, 92, 10, 38],
    ratingAvg: 4.8,
    ratingCount: 402,
  },
  {
    id: "molecule-01",
    slug: "molecule-01",
    name: "Molecule 01",
    brand: "Escentric Molecules",
    brandSlug: "escentric-molecules",
    sourceUrl: "https://www.fragrantica.com",
    country: "Germany",
    imageUrl: "https://images.unsplash.com/photo-1600612253971-422e7f7faeb6?auto=format&fit=crop&w=800&q=80",
    gender: "men",
    year: 2006,
    concentration: "EDT",
    perfumers: ["Geza Schoen"],
    topNotes: ["Iso E Super"],
    midNotes: ["Iso E Super"],
    baseNotes: ["Iso E Super"],
    families: ["Woody", "Musky", "Fresh"],
    longevity: 6.8,
    projection: 4.8,
    seasons: ["Spring", "Summer", "Fall"],
    occasions: ["Daily", "Office", "Layering"],
    impressions: ["Minimal", "Clean", "Skin Scent"],
    priceRange: "$$$",
    scentVector: [58, 44, 0, 10, 0, 0, 0, 82, 8, 0, 0, 0, 0, 0],
    ratingAvg: 4.1,
    ratingCount: 522,
  },
  {
    id: "angel-s-share",
    slug: "angel-s-share",
    name: "Angels' Share",
    brand: "Kilian",
    brandSlug: "kilian",
    sourceUrl: "https://www.fragrantica.com",
    country: "France",
    imageUrl: "https://images.unsplash.com/photo-1615634262417-99c4f04f0a89?auto=format&fit=crop&w=800&q=80",
    gender: "unisex",
    year: 2020,
    concentration: "EDP",
    perfumers: ["Benoist Lapouza"],
    topNotes: ["Cognac"],
    midNotes: ["Cinnamon", "Tonka Bean", "Oak"],
    baseNotes: ["Praline", "Vanilla", "Sandalwood"],
    families: ["Sweet", "Amber", "Spicy"],
    longevity: 9.2,
    projection: 7.9,
    seasons: ["Fall", "Winter"],
    occasions: ["Date Night", "Night Out", "Special"],
    impressions: ["Decadent", "Cozy", "Addictive"],
    priceRange: "$$$$",
    scentVector: [4, 18, 82, 0, 42, 0, 0, 8, 64, 72, 0, 0, 12, 36],
    ratingAvg: 4.7,
    ratingCount: 615,
  },
  {
    id: "philosykos-edp",
    slug: "philosykos-edp",
    name: "Philosykos",
    brand: "Diptyque",
    brandSlug: "diptyque",
    sourceUrl: "https://www.fragrantica.com",
    country: "France",
    imageUrl: "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=800&q=80",
    gender: "unisex",
    year: 2012,
    concentration: "EDP",
    perfumers: ["Olivia Giacobetti"],
    topNotes: ["Fig Leaf", "Fig"],
    midNotes: ["Coconut", "Green Notes"],
    baseNotes: ["Cedar", "Woody Notes"],
    families: ["Green", "Woody", "Fresh"],
    longevity: 7.0,
    projection: 5.0,
    seasons: ["Spring", "Summer"],
    occasions: ["Daily", "Office", "Weekend"],
    impressions: ["Green", "Airy", "Artful"],
    priceRange: "$$$",
    scentVector: [60, 42, 10, 16, 0, 12, 0, 18, 6, 6, 0, 8, 0, 0],
    ratingAvg: 4.6,
    ratingCount: 287,
  },
];

export const mockProfile: UserProfile = {
  id: "demo-user",
  email: "demo@scentify.app",
  fullName: "Mucahit",
  bio: "Fresh woods, clean musks, soft amber.",
  location: "Istanbul",
  onboardingCompleted: false,
  isPremium: false,
  premiumExpiresAt: null,
  weatherEnabled: true,
};

export const mockDNA: ScentDNAProfile = {
  ...vectorFromArray([86, 72, 24, 58, 28, 40, 18, 62, 32, 14, 8, 22, 4, 12]),
  profileTags: ["Clean", "Fresh", "Woody", "Modern", "Everyday"],
  bestFamilies: ["Fresh Aromatic", "Woody Citrus", "Musky Woods"],
  avoidNotes: ["Dense Tobacco", "Heavy Oud"],
  summary: "You gravitate toward clean, fresh fragrances with woody depth and a polished musky trail.",
};

export const mockWeather: WeatherSnapshot = {
  city: "Istanbul",
  temp: 18,
  condition: "Clear",
};

export const mockBrands: Brand[] = [
  { id: "brand-chanel", slug: "chanel", name: "Chanel", country: "France", perfumeCount: 1 },
  { id: "brand-le-labo", slug: "le-labo", name: "Le Labo", country: "United States", perfumeCount: 1 },
  {
    id: "brand-maison-francis-kurkdjian",
    slug: "maison-francis-kurkdjian",
    name: "Maison Francis Kurkdjian",
    country: "France",
    perfumeCount: 2,
  },
  { id: "brand-jo-malone", slug: "jo-malone", name: "Jo Malone", country: "United Kingdom", perfumeCount: 1 },
  { id: "brand-dior", slug: "dior", name: "Dior", country: "France", perfumeCount: 1 },
];

export const mockPerfumers: Perfumer[] = [
  {
    id: "perfumer-jacques-polge",
    slug: "jacques-polge",
    name: "Jacques Polge",
    perfumeCount: 1,
    signatureFamilies: ["Fresh", "Woody", "Citrus"],
    brands: ["Chanel"],
  },
  {
    id: "perfumer-francis-kurkdjian",
    slug: "francis-kurkdjian",
    name: "Francis Kurkdjian",
    perfumeCount: 2,
    signatureFamilies: ["Amber", "Musky", "Fresh"],
    brands: ["Maison Francis Kurkdjian"],
  },
  {
    id: "perfumer-nathalie-lorson",
    slug: "nathalie-lorson",
    name: "Nathalie Lorson",
    perfumeCount: 1,
    signatureFamilies: ["Musky", "Fresh", "Amber"],
    brands: ["Le Labo"],
  },
  {
    id: "perfumer-christine-nagel",
    slug: "christine-nagel",
    name: "Christine Nagel",
    perfumeCount: 1,
    signatureFamilies: ["Aquatic", "Fresh", "Woody"],
    brands: ["Jo Malone"],
  },
];
